# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the relevant issue template!
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines [here](https://github.com/farhan7reza7/diff-ymd-package/blob/main/CONTRIBUTING.md).

# Comment to be posted to on Pr's merged by a first time user
firstPRMergeComment: >
